# Generated by Django 3.2.6 on 2021-12-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorizer',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
