# Generated by Django 3.2.6 on 2021-12-23 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponder', '0013_alter_categorizer_name_not_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorizer',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
