name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
# Disabling tests for now as it requires a DB to connect to.
#    - name: Run Tests
#      run: |
#        python manage.py test ponder.tests
